version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: Phfn3EhEMRaFpr4ixacGKVQzu8m9fsy3tIqjYNNuhvqsd6ZfJ2m1XuE8shKX3ADz
  skip_symbols: true
  artifact: /.*\.nupkg/
- provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only