version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: Phfn3EhEMRaFpr4ixacGKVQzu8m9fsy3tIqjYNNuhvqsd6ZfJ2m1XuE8shKX3ADz
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/