version: 0.3.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: Wire\**\AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: Wire\**\*.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Wire\bin\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: eP+2nbmIVATRw1icTU05LJshve/BY1qNE0zpjLR9tojXPh8zD61Ftkpv8VJZLF9U
  skip_symbols: true