version: 0.3.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Wire\bin\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: eP+2nbmIVATRw1icTU05LJshve/BY1qNE0zpjLR9tojXPh8zD61Ftkpv8VJZLF9U
  skip_symbols: true
